In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
%run "./age-filter.py"
%run "./baby-appender.py"
%run "./cabin-converter.py"
%run "./family-size-appender.py"
%run "./nd-fare-appender.py"

In [16]:
from sklearn.model_selection import train_test_split

titanic = pd.read_csv('./titanic/train.csv')
train, test = train_test_split(titanic, test_size=0.2, random_state=39)

y_train = train["Survived"]
X_train = train.drop("Survived", axis=1)

y_test = test["Survived"]
X_test = test.drop("Survived", axis=1)

In [5]:
# fare_bins = np.arange(0, 7, 14)
age_bins = np.arange(0, 100, 5)
cabins = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'T', np.nan]

In [13]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import StandardScaler
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.pipeline import Pipeline

# col_transformer = ColumnTransformer([ 
#   ("onehot", OneHotEncoder(), ["Pclass", "Sex", "Family_bin"]),
#   ("fare", OneHotEncoder(categories=[fare_bins]), ["Fare_nd_bin"]),
#   ("age", OneHotEncoder(categories=[age_bins]), ["Age_bin"]),
#   ("floor", OneHotEncoder(categories=[cabins]), ["Floor"]),
#   ("passthrough", "passthrough", ["Baby"]),
# ])

In [41]:
imputer = SimpleImputer()
titanic_imputed = imputer.fit_transform(titanic[["Age", "Fare"]])
titanic_imputed

array([[22.        ,  7.25      ],
       [38.        , 71.2833    ],
       [26.        ,  7.925     ],
       ...,
       [29.69911765, 23.45      ],
       [26.        , 30.        ],
       [32.        ,  7.75      ]])

In [44]:
_df = pd.DataFrame(titanic_imputed)
_df[_df.isna().any(axis=1)]

Empty DataFrame
Columns: [0, 1]
Index: []

In [51]:
pd.Series(pd.cut(titanic_imputed[:, 0], age_bins)).value_counts()

(25, 30]    285
(20, 25]    122
(15, 20]     96
(30, 35]     88
(35, 40]     67
(40, 45]     47
(0, 5]       44
(45, 50]     39
(50, 55]     24
(5, 10]      20
(10, 15]     19
(55, 60]     18
(60, 65]     14
(70, 75]      4
(65, 70]      3
(75, 80]      1
(80, 85]      0
(85, 90]      0
(90, 95]      0
dtype: int64

In [34]:
# from sklearn.base import BaseEstimator, TransformerMixin
# from sklearn.impute import SimpleImputer

# class Binner(BaseEstimator, TransformerMixin):

#   def __init__(self):
#     self.imputer = SimpleImputer()
#     return

#   def fit(self, X, y=None):
#     return self
  
#   def transform(self, X, y=None):
#     X_imputed = self.imputer.fit_transform(X[["Age", "Fare_nd"]])

#     _X = X.assign(Family_bin=pd.cut(X["Family"], [0, 1, 4, 7, np.Infinity], labels=['solo', 'small', 'middle', 'large']))
#     _X = _X.assign(Age_bin=pd.cut(X_imputed[:, 0], age_bins))
#     _X = _X.assign(Fare_nd_bin=pd.cut(X_imputed[:, 1], fare_bins))
#     return _X


In [35]:
# from sklearn.pipeline import Pipeline

# dataframe_pipeline = Pipeline([
#   ('baby', BabyAppender(limit=20)),
#   ('cabin', CabinConverter()),
#   ('group', FamilySizeAppender()),
#   ('fare', NDFareAppender()),
#   ('bin', Binner()),
# ])

In [52]:
dataframe_pipeline.fit_transform(X_train)

PassengerId  Pclass                                               Name  \
129          130       3                                 Ekstrom, Mr. Johan   
793          794       1                           Hoyt, Mr. William Fisher   
701          702       1                   Silverthorne, Mr. Spencer Victor   
601          602       3                               Slabenoff, Mr. Petco   
344          345       2                            Fox, Mr. Stanley Hubert   
..           ...     ...                                                ...   
582          583       2                         Downton, Mr. William James   
64            65       1                              Stewart, Mr. Albert A   
41            42       2  Turpin, Mrs. William John Robert (Dorothy Ann ...   
105          106       3                              Mionoff, Mr. Stoytcho   
393          394       1                             Newell, Miss. Marjorie   

        Sex   Age  SibSp  Parch    Ticket      Fare Embarked   Baby Floor  \
129    male  45.0      0      0    347061    6.9750        S  False   NaN   
793    male   NaN      0      0  PC 17600   30.6958        C  False   NaN   
701    male  35.0      0      0  PC 17475   26.2875        S  False     E   
601    male   NaN      0      0    349214    7.8958        S  False   NaN   
344    male  36.0      0      0    229236   13.0000        S  False   NaN   
..      ...   ...    ...    ...       ...       ...      ...    ...   ...   
582    male  54.0      0      0     28403   26.0000        S  False   NaN   
64     male   NaN      0      0  PC 17605   27.7208        C  False   NaN   
41   female  27.0      1      0     11668   21.0000        S  False   NaN   
105    male  28.0      0      0    349207    7.8958        S  False   NaN   
393  female  23.0      1      0     35273  113.2750        C  False     D   

     CabinNumber  Family   Fare_nd Family_bin   Age_bin Fare_nd_bin  
129          NaN       1  2.076312       solo  (40, 45]         NaN  
793          NaN       1  3.456184       solo  (25, 30]         NaN  
701         24.0       1  3.306429       solo  (30, 35]         NaN  
601          NaN       1  2.185579       solo  (25, 30]         NaN  
344          NaN       1  2.639057       solo  (35, 40]         NaN  
..           ...     ...       ...        ...       ...         ...  
582          NaN       1  3.295837       solo  (50, 55]         NaN  
64           NaN       1  3.357622       solo  (25, 30]         NaN  
41           NaN       2  3.091042      small  (25, 30]         NaN  
105          NaN       1  2.185579       solo  (25, 30]         NaN  
393         36.0       2  4.738608      small  (20, 25]         NaN  

[712 rows x 18 columns]

In [58]:
pd.Series(titanic_imputed[:, 1])

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Length: 891, dtype: float64

In [78]:
_titanic = NDFareAppender().fit_transform(titanic)
imputer = SimpleImputer()
titanic_imputed = imputer.fit_transform(_titanic[["Age", "Fare_nd"]])
titanic_imputed

array([[22.        ,  2.1102132 ],
       [38.        ,  4.28059312],
       [26.        ,  2.18885633],
       ...,
       [29.69911765,  3.19663022],
       [26.        ,  3.4339872 ],
       [32.        ,  2.1690537 ]])

In [82]:
pd.Series(titanic_imputed[:, 1]).describe()

count    891.000000
mean       2.962246
std        0.969048
min        0.000000
25%        2.187218
50%        2.737881
75%        3.465736
max        6.240917
dtype: float64

In [84]:
fare_bins = np.arange(0, 8, .5)
fare_bins

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5])

In [87]:
pd.Series(pd.cut(titanic_imputed[:, 1], fare_bins)).value_counts()

(2.0, 2.5]    349
(3.0, 3.5]    173
(2.5, 3.0]    140
(4.0, 4.5]     78
(3.5, 4.0]     70
(4.5, 5.0]     34
(5.0, 5.5]     18
(5.5, 6.0]      8
(1.5, 2.0]      3
(6.0, 6.5]      3
(0.0, 0.5]      0
(0.5, 1.0]      0
(1.0, 1.5]      0
(6.5, 7.0]      0
(7.0, 7.5]      0
dtype: int64

In [106]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

class Binner(BaseEstimator, TransformerMixin):

  def __init__(self):
    self.imputer = SimpleImputer()
    self.label_encoder = LabelEncoder()
    return

  def fit(self, X, y=None):
    return self
  
  def transform(self, X, y=None):
    X_imputed = self.imputer.fit_transform(X[["Age", "Fare_nd"]])

    _X = X.assign(Family_bin=pd.cut(X["Family"], [0, 1, 4, 7, np.Infinity], labels=['solo', 'small', 'middle', 'large']))

    age_bin = pd.cut(X_imputed[:, 0], age_bins)
    age_bin_label = self.label_encoder.fit_transform(age_bin)
    _X = _X.assign(Age_bin=age_bin_label)

    fare_bin = pd.cut(X_imputed[:, 1], fare_bins)
    fare_bin_label = self.label_encoder.fit_transform(fare_bin)
    _X = _X.assign(Fare_nd_bin=fare_bin_label)
    return _X


In [107]:
from sklearn.pipeline import Pipeline

dataframe_pipeline = Pipeline([
  ('baby', BabyAppender(limit=20)),
  ('cabin', CabinConverter()),
  ('group', FamilySizeAppender()),
  ('fare', NDFareAppender()),
  ('bin', Binner()),
])

In [108]:
_X_train = dataframe_pipeline.fit_transform(X_train)
_X_train

PassengerId  Pclass                                               Name  \
129          130       3                                 Ekstrom, Mr. Johan   
793          794       1                           Hoyt, Mr. William Fisher   
701          702       1                   Silverthorne, Mr. Spencer Victor   
601          602       3                               Slabenoff, Mr. Petco   
344          345       2                            Fox, Mr. Stanley Hubert   
..           ...     ...                                                ...   
582          583       2                         Downton, Mr. William James   
64            65       1                              Stewart, Mr. Albert A   
41            42       2  Turpin, Mrs. William John Robert (Dorothy Ann ...   
105          106       3                              Mionoff, Mr. Stoytcho   
393          394       1                             Newell, Miss. Marjorie   

        Sex   Age  SibSp  Parch    Ticket      Fare Embarked   Baby Floor  \
129    male  45.0      0      0    347061    6.9750        S  False   NaN   
793    male   NaN      0      0  PC 17600   30.6958        C  False   NaN   
701    male  35.0      0      0  PC 17475   26.2875        S  False     E   
601    male   NaN      0      0    349214    7.8958        S  False   NaN   
344    male  36.0      0      0    229236   13.0000        S  False   NaN   
..      ...   ...    ...    ...       ...       ...      ...    ...   ...   
582    male  54.0      0      0     28403   26.0000        S  False   NaN   
64     male   NaN      0      0  PC 17605   27.7208        C  False   NaN   
41   female  27.0      1      0     11668   21.0000        S  False   NaN   
105    male  28.0      0      0    349207    7.8958        S  False   NaN   
393  female  23.0      1      0     35273  113.2750        C  False     D   

     CabinNumber  Family   Fare_nd Family_bin  Age_bin  Fare_nd_bin  
129          NaN       1  2.076312       solo        8            1  
793          NaN       1  3.456184       solo        5            3  
701         24.0       1  3.306429       solo        6            3  
601          NaN       1  2.185579       solo        5            1  
344          NaN       1  2.639057       solo        7            2  
..           ...     ...       ...        ...      ...          ...  
582          NaN       1  3.295837       solo       10            3  
64           NaN       1  3.357622       solo        5            3  
41           NaN       2  3.091042      small        5            3  
105          NaN       1  2.185579       solo        5            1  
393         36.0       2  4.738608      small        4            6  

[712 rows x 18 columns]

In [111]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

cabins = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'T', np.nan]

scaler_pipeline = Pipeline([
  ('imputer', SimpleImputer()),
  ('std_scaler', StandardScaler()),
])

col_transformer = ColumnTransformer([ 
  ("onehot", OneHotEncoder(), ["Pclass", "Sex", "Family_bin", "Fare_nd_bin", "Age_bin"]),
  ("floor", OneHotEncoder(categories=[cabins]), ["Floor"]),
  ("passthrough", "passthrough", ["Baby"]),
])

In [112]:
whole_pipeline = Pipeline([
  ('dataframe', dataframe_pipeline),
  ('std_scaler', col_transformer),
])

In [113]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

_X_train = whole_pipeline.fit_transform(X_train)
clf = RandomForestClassifier(random_state=38)
clf.fit(_X_train, y_train)
cross_val_score(clf, _X_train, y_train, cv=3, scoring="accuracy")

array([0.81932773, 0.76371308, 0.81012658])

In [114]:
from sklearn.model_selection import GridSearchCV

param_grid = [
  { 
    # "criterion": ["gini", "entropy"],
    # "class_weight": ["balanced"],
    # "max_features": ["sqrt", "log2"],
    "max_features": [16],
    "min_samples_split": [14, 16, 18, 20],
    "n_estimators": [90, 100, 110],
  }
]

grid_search = GridSearchCV(
  RandomForestClassifier(random_state=38),
  param_grid,
  cv=5,
  scoring="accuracy",
  return_train_score=True)
grid_search.fit(_X_train, y_train)

grid_search.best_score_, grid_search.best_params_

(0.8215601300108343,
 {'max_features': 16, 'min_samples_split': 18, 'n_estimators': 100})

In [115]:
_X_test = whole_pipeline.fit_transform(X_test)
cross_val_score(grid_search.best_estimator_, _X_test, y_test, cv=3, scoring="accuracy")

array([0.8       , 0.81666667, 0.71186441])

In [117]:
titanic_test = pd.read_csv('./titanic/test.csv')

In [119]:
_titanic_test = whole_pipeline.fit_transform(titanic_test)
predict = grid_search.best_estimator_.predict(_titanic_test)

id = np.array(titanic_test["PassengerId"]).astype(int)
df = pd.DataFrame(predict, id, columns = ["Survived"])
df.to_csv("./titanic/predict-8.csv", index_label = ["PassengerId"])

In [121]:
from sklearn.pipeline import Pipeline

dataframe_pipeline = Pipeline([
  # ('baby', BabyAppender(limit=20)),
  ('cabin', CabinConverter()),
  ('group', FamilySizeAppender()),
  ('fare', NDFareAppender()),
  ('bin', Binner()),
])

In [122]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

cabins = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'T', np.nan]

scaler_pipeline = Pipeline([
  ('imputer', SimpleImputer()),
  ('std_scaler', StandardScaler()),
])

col_transformer = ColumnTransformer([ 
  ("onehot", OneHotEncoder(), ["Pclass", "Sex", "Family_bin", "Fare_nd_bin", "Age_bin"]),
  ("floor", OneHotEncoder(categories=[cabins]), ["Floor"]),
  # ("passthrough", "passthrough", ["Baby"]),
])

In [123]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

_X_train = whole_pipeline.fit_transform(X_train)
clf = RandomForestClassifier(random_state=38)
clf.fit(_X_train, y_train)
cross_val_score(clf, _X_train, y_train, cv=3, scoring="accuracy")

array([0.81932773, 0.76371308, 0.81012658])

In [125]:
from sklearn.model_selection import GridSearchCV

param_grid = [
  { 
    "max_features": [14, 16, 18, 20],
    "min_samples_split": [14, 16, 18, 20],
    "n_estimators": [90, 100, 110],
  }
]

grid_search = GridSearchCV(
  RandomForestClassifier(random_state=38),
  param_grid,
  cv=5,
  scoring="accuracy",
  return_train_score=True)
grid_search.fit(_X_train, y_train)

grid_search.best_score_, grid_search.best_params_

(0.8215601300108343,
 {'max_features': 16, 'min_samples_split': 18, 'n_estimators': 100})

In [126]:
_X_test = whole_pipeline.fit_transform(X_test)
cross_val_score(grid_search.best_estimator_, _X_test, y_test, cv=3, scoring="accuracy")

array([0.8       , 0.81666667, 0.71186441])

In [127]:
file = "./titanic/predict-8-2.csv"
_titanic_test = whole_pipeline.fit_transform(titanic_test)
predict = grid_search.best_estimator_.predict(_titanic_test)

id = np.array(titanic_test["PassengerId"]).astype(int)
df = pd.DataFrame(predict, id, columns = ["Survived"])
df.to_csv(file, index_label = ["PassengerId"])